#server:
#  error:
#    include-message: always
#    include-binding-errors: always
#    include-stacktrace: never
#  port: 8080
#  servlet:
#    context-path: /car-rental/api
#
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    password: postgres
#    username: postgres
#    url: jdbc:postgresql://localhost:5432/CarRental
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgresSQLDialect
#        format_sql: true
#        show-sql: true
#server:
#  error:
#    include-binding-errors: always
#    include-stacktrace: never
#    include-message: always
#  port: 8080 #port decided
#  servlet: # URL path decided. Means the url path we want
#    context-path: /car-rental/api
#
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    password: postgres
#    username: postgres
#    url: jdbc:postgresql://localhost:5432/CarRental
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    show-sql: true
#
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
#    default-property-inclusion: non_null
#
#  servlet:
#    multipart:
#      max-file-size: 2MB
#      max-request-size: 2MB

server:
  port: 8080
  error:
    include-stacktrace: never
  servlet:
    context-path: /car-rental/api


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prorent_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect # we are adding this to tell other platforms to use postgre

#  security:
#    user:
#      name: postgres
#      password: postgres
logging:
  file:
    name: logs/prorent.log # We are gonna log everything
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
    level:
      org.springframework.web: DEBUG # We will log if we run in the debug mode.
      com.prorental: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE